# Generated by Django 3.0.7 on 2020-07-07 08:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PublicRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('display', models.BooleanField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('displaytype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tv.DisplayType')),
            ],
        ),
    ]
